final commit

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -1,31 +1,74 @@
 pipeline{
-    agent {label 'frontend'}
+    agent any
     environment {
-            APP-SERVER = "172.31.40.178"
-            DEPLOY_DIR = "/var/www/html"
+            IMAGE_NAME = "pandu245/frontend"
+            IMAGE_TAG  = "${BUILD-NUMBER}"
+            APP_SERVER = "16.170.243.86"
     }
     stages{
-        stage('Pre Build Actions'){
+        stage('Checkout'){
             steps{
-                    sh 'npm install'
+                    git branch: 'main',
+                    url: 'https://github.com/Pandu2451M/jenkins-webapp.git'
             }
         }
-        stage('Build'){
+        stage('Build Docker Image'){
             steps{
-                    sh 'npm run build'
+                    sh '''
+                    docker build -f docker/dockerfile -t $IMAGE_NAME:$IMAGE_TAG .
+                    '''
             }
         }
-        stage('Post Build Actions'){
+        stage('Docker Login'){
             steps{
-                    sh """
-                    echo 'Cleaning old files on app server'
-                    ssh jenkins@${APP_SERVER} 'rm-rf ${DEPLOY_DIR}/*'
-                    echo 'Copying frontend build'
-                    scp -r dist/* jenkins@${APP_SERVER}:${DEPLOY-DIR}/
-                    echo 'Restarting nginx'
-                    ssh jenkins@${APP_SERVER} 'sudo systemctl restart nginx'
-                    """
+                    withCredentials([
+                        usernamePassword(
+                            credentialsID: 'dockerCred',
+                            usernamevariable: 'DOCKER_USER',
+                            passwordVariables: 'DOCKER_PASS'
+                        )
+                    ])  {
+                        sh '''
+                        echo $DOCKER_PASS | docker login \
+                        -u $DOCKER_USER \
+                        --password-stdin
+                        '''
+                    }
+                }
+        }                                   
+        stage('Push Image'){
+            steps{
+                sh '''
+                docker push $IMAGE_NAME:$IMAGE_TAG
+                docker tag \
+                $IMAGE_NAME:$IMAGE_TAG \
+                $IMAGE_NAME:latest
+                docker push $IMAGE_NAME:latest
+                '''
             }
+        }
+        stage('Deploy To App Server'){
+            steps{
+                sh """
+                ssh ubuntu@$APP_SERVER '
+                docker pull $IMAGE_NAME:latest
+                docker stop frontend || true 
+                docker rm frontend || true 
+                docker run -d \
+                --name frontend \
+                -p 80:80 \
+                $IMAGE_NAME:latest
+                '
+                """
+            }
+        }
+    }
+    post {
+        sucess {
+            echo "Deployment Sucessful"
+        }
+        failure {
+            echo "Deployment Failed"
         }
     }
 }
